#Welcome to OfflinePlayers
#This Plugin spawns a clone from a Player if he is offline at his logout location!
#Here you can configure the plugin and the behavior of the offline clones.

OfflinePlayer:
  cloneEntity: ZOMBIE #The entity type of the clone. You can find a list of all entity types here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
  #If you want to use the entity type of PLAYER you need to install the Citizens plugin and set the cloneEntity to PLAYER.
  spawnOnCreative: false #If true the clone will spawn when the player is in creative mode.
  isHittable: true #If the clone is damageable.
  hasAI: true #If true the clone is able to be fall down, pushed or knocked back.
  nameAlwaysVisible: true #If false the name of the clone is only visible if you hover on it.
  name: "§8§lOffline §7- §c%PLAYER_NAME §e%DESPAWN_TIMER%" #The name of the clone. %PLAYER_NAME will be replaced with the name of the player. %DESPAWN_TIMER% will be replaced with the time until the clone despawns.
  de-spawnTimer:
    enabled: true
    timer: 20 #The time in seconds the clone is de-spawned after it is spawned.
  worldBlacklist: #A list of worlds where the clones will not spawn.
    - world1
    - world2
    - world3
  permissions: #If enabled players will only get a clone if they have the permission.
    enabled: false
    permission: 'offlineplayer.clone'